module.exports =
  id: 1
  developerId: 1
  key: 'validgamekey'
  name: 'GAME_NAME'
  description: 'GAME_DESCRIPTION'
  icon128Url: 'http://someurl.com/valid_icon_128.png'
  promo440Url: 'http://someurl.com/valid_promo_440.png'
  rating: 4.4
  gameUrl: 'http://validgameurl.com'
  orientation: 'portrait'
  isMobile: false
  isDesktop: false
  headerImage: 'http://someurl.com/valid_header_image.png'
  iconImage: 'http://someurl.com/valid_header_image.png'
  screenshotImages: ['http://someurl.com/valid_screenshot_image.png']
  status: 'Approved'
  category: 'action'
